version: "3"

services:
  backend:
    container_name: backend
    build: ./docker/nodeDocker
    ports:
      - 3000:3000
    volumes:
      - .:/home/node/app
    depends_on:
      db:
        condition: service_healthy
    restart: always

  db:
    image: mysql
    container_name: mysql
    ports:
    - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: nest
    command: ['mysqld', '--character-set-server=utf8', '--collation-server=utf8_unicode_ci']
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      interval: 5s
      timeout: 10s
      retries: 5

  phpadmin:
    container_name: phpadmin
    image: phpmyadmin
    restart: always
    ports:
    - 8080:80
    environment:
      PMA_PORT: 3306
      PMA_PASSWORD: root
      PMA_USER: root

